<?php
include('libreria.php');
include_once('clases/Articulo.php');
include_once('db/searchs.php');
conectarDB();
$nombre=$_REQUEST['nombre'];
$articulo=buscarArticulo($nombre);
include('eliminarArticuloShow.php');
?>